config/exercise_readme.go.tmpl, exercises/bob/README.md, exercises/difference-of-squares/README.md, exercises/gigasecond/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/rna-transcription/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
=> Generate static exercise README templates

README.md
As noted by @kytrinyx in https://github.com/exercism/dart/issues/2#issuecomment-322084238, I added a link to the style guide and the filename convention.
As I did that, I noticed a note about adding a link to the language's formatter within the README. So I added that as well.
=> Add references to formatter tool and Dart conventions

exercises/bob/test/bob_test.dart
Noticed we decode one string, but not the other.
Also not sure if we want to move the decoded string comment to the test where the string resides.
=> Update comment in Bob to decode other string

exercises/bob/pubspec.lock, exercises/bob/pubspec.yaml, exercises/difference-of-squares/pubspec.lock, exercises/difference-of-squares/pubspec.yaml, exercises/gigasecond/pubspec.lock, exercises/gigasecond/pubspec.yaml, exercises/hamming/pubspec.lock, exercises/hamming/pubspec.yaml, exercises/hello-world/pubspec.lock, exercises/hello-world/pubspec.yaml, exercises/hello-world/test/hello_world_test.dart, exercises/leap/pubspec.lock, exercises/leap/pubspec.yaml, exercises/rna-transcription/pubspec.lock, exercises/rna-transcription/pubspec.yaml
Addresses #27 
I also bumped the test version to 0.12.24+1. Not sure if we would be okay with setting a [version constraint](https://www.dartlang.org/tools/pub/dependencies#version-constraints) to the test framework can go up to, but not including, 0.13.0.
We can do this by setting the version for test to be `<0.13.0`, then that gives us some breathing room and we don't have to think about updating the dependencies so often.
=> Revise Hello World to serve as a simple example for future test suites

config.json, config/maintainers.json
Discussed in #37.
Reordering the exercises and labeling them as core. The exercises are now unlocked after completing the previous exercise. Also addressed duplicate uuids configlet found
* Hello World (difficulty - 1)
* Leap (difficulty - 1)
* Difference of Squares (difficulty - 2)
* Bob (difficulty - 2)
* Hamming (difficulty - 2)
* Gigasecond (difficulty - 3)
* RNA-Transcription (difficulty - 3)
@fwip Would feel like reviewing?
=> Reorder exercises based on discussion

exercises/anagram/test/anagram_test.dart, exercises/rna-transcription/test/rna_transcription_test.dart
Two test suites are referencing "example.dart" which is the solution to the given problem. Nothing is leaked to the user, because the file is not included when users fetch the problem.
But we shouldn't include errors into our user's test suites, so we should remove it.
@exercism/dart or @fwip care to check me over?
=> Some Test suites accidentally reference the example.dart file

.travis.yml, bin/check_formatting, exercises/bob/pubspec.lock, exercises/difference-of-squares/pubspec.lock, exercises/gigasecond/pubspec.lock, exercises/hamming/pubspec.lock, exercises/hello-world/pubspec.lock, exercises/leap/pubspec.lock, exercises/rna-transcription/pubspec.lock, exercises/rna-transcription/test/rna_transcription_test.dart, pubspec.lock, pubspec.yaml, test/exercises_test.dart
Implementation of #34. Add a command to travis to run the tests.
@SuperPaintman already had a script to run all tests. But since that was also a test, the final results were not separated from the test results of the last exercise. So I added a statement in between.
Additionally updated the repo's package dependencies to reflect the changes to versioning we made for the exercises.
***Note to Reviewer***: No changes to Travis Settings requested
=> Run all tests in Travis and revise dependency versions

config.json
Apparently, I had a few typos. @fwip fixed the unlocked value and I never noticed the "core" parameter was false. So resolving that.
=> Make Anagram a core track

tool/create-exercise
This pull request adds a `--spec-path` argument to `tool/create-exercise`. If given a path to a checkout of https://github.com/exercism/problem-specifications , it will use the information in `canonical-data.json` to generate tests.  (I chose `--spec-path` after the option in `bin/configlet generate`).
Example usage:
`dart tool/create-exercise --spec-path ../problem-specifications/ beer-song`
It doesn't work for every `canonical-data.json` out there, and some others will need some light editing to get into the proper format.  But it could be useful if we're trying to crank out a bunch of regular-ish exercises.
What do you think @Stargator ?
=> Generate tests

CONTRIBUTING.md, README.md
I just created a chat room. You can visit it here: [https://gitter.im/exercism/dart](https://gitter.im/exercism/dart?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).
This pull-request adds this badge to your README.md:
[![Gitter](https://badges.gitter.im/exercism/dart.svg)](https://gitter.im/exercism/dart?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
If my aim is a little off, please let me know.
I figured a gitter room would be easier than a discussing in random pull requests or issues.
PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.
=> Update README with new badge and a revised contributing section

exercises/leap/test/leap_test.dart
Another fix for the leap exercise. The reasoning is listed below in a pull request in the [problem-specifications](https://github.com/exercism/problem-specifications/pull/971#issuecomment-339312341) and [the python track](https://github.com/exercism/python/pull/979)
=> Refine leap to address a loophole

tool/create-exercise
This closes #62.
Not a lot of exciting things going on in this pull request. Generates `README.md` using `configlet generate`, and factors out a pattern for running processes.
=> create-exercise can generate README.md

test/exercises_test.dart
Just a bit of polishing up. The commenting didn't follow Dart standard of three slashes for documentation.
And a few variable names need to be updated. Constants follow lower camelcase like all variables.
=> Fix commenting for Dart standard, rename variables

exercises/phone-number/test/phone_number_test.dart
The linting from #75 found the return type missing for these functions. Addressing it will also allow the test suite to match how the other test suites for exercises do this.
=> Address lint rule error for always_declare_return_types

analysis_options.yaml
Revise the analysis-options.yaml file with some lint rules to prevent errors. Will be useful as the project grows.
=> Add linting rules for errors

config.json
The previous version of `configlet uuid` was known to generate invalid UUIDs. The latest release of Configlet [v3.6.1](https://github.com/exercism/configlet/releases) fixes that issue for newly added exercises, but existing exercise UUIDs need to be updated manually.
This change pertains to exercism/configlet#99
=> Fix invalid exercise UUID

exercises/bob/.meta/description.md, exercises/bob/README.md
We need to be able to regenerate the exercise READMEs without
causing the README for 'bob' to drift.
A new rule has been added to the upstream problem specification,
and this hasn't yet been implemented in this track.
I only realized after submitting https://github.com/exercism/dart/issues/100 that I needed to regenerate the exercise READMEs in order to move forward with https://github.com/exercism/meta/issues/94, which would cause 'bob' to get out of sync.
Since this is a purely janitorial change, I am going to go ahead and merge it when the build passes.
I'm adding a note to the ambiguity issue about deleting this file when the test suite gets updated.
=> bob: Lock problem description to match current implementation

config/exercise_readme.go.tmpl, docs/EXERCISE_README_INSERT.md, exercises/anagram/README.md, exercises/difference-of-squares/README.md, exercises/gigasecond/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/phone-number/.meta/hints.md, exercises/phone-number/README.md, exercises/raindrops/README.md, exercises/rna-transcription/README.md, exercises/word-count/README.md
Now that we're operating with a track-wide template for generating exercise
READMEs we no longer need a separate markdown document to use for hints
and instructions that apply to all the exercises in a track. These instructions
can be defined directly in the template.
The first commit regenerates the exercise READMEs to pick up tweaks to problem descriptions, which have been updated with various formatting changes, whitespace changes, and clarifications to the description.
That gives us a clean diff when inlining the template and regenerating.
Ref: https://github.com/exercism/meta/issues/94
=> Inline the exercise README insert

exercises/leap/test/leap_test.dart
I added more test cases to account for dates less than 400 years old. I also wasn't sure why `skip: true` was being set on every test so I removed those.
=> leap: add more test cases

exercises/armstrong-numbers/lib/example.dart, pubspec.lock
The dependency in the pubspec.lock file is off and there's a formatting issue in armstrong-numbers.
Addressing these minor issues will help by preventing false negatives and making it easier to run the tests without running `pub get`
=> dart-exercism: Fix formatting and dependency issues

config/maintainers.json
@kabiir changed their username to @devkabiir.
We rely on the correct username to get the data for the maintainers
page, and to link to the GitHub profile.
FYI @Stargator - I'm merging this, as it's breaking a script that we're running regularly.
=> Update maintainer username

README.md, test/exercises_test.dart
I don't have a Windows machine to run the tests on, so I cannot verify that `pub run test` works in Windows.
I have noticed that MacOS was producing files with "-e" or "e" appended to the extension, so I resolved that.
=> Compensate when tests are executed on MacOS

config/exercise_readme.go.tmpl, exercises/anagram/README.md, exercises/armstrong-numbers/README.md, exercises/bob/README.md, exercises/difference-of-squares/README.md, exercises/gigasecond/README.md, exercises/hamming/README.md, exercises/hello-world/README.md, exercises/leap/README.md, exercises/phone-number/README.md, exercises/raindrops/README.md, exercises/rna-transcription/README.md, exercises/scrabble-score/README.md, exercises/word-count/README.md
Changed help links to point directly to the documentation pages - I've included the two most important pages, and other pages can be found on the bottom of the doc pages or via the bottom right of solution pages.
Fixes #143
=> Updated links to help resources

docs/INSTALLATION.md
=> dart: Install link should point to SDK installation guide

bin/create_exercise.dart, test/exercises_test.dart
The Dart Analyzer has been giving some errors when casting some variables or values.
They did not prevent the tests or other scripts from running successfully, but I still wanted to address them to prevent confusion.
I've addressed them and formatted the files I changed.
Additionally, I added the .dart_tool directory to the ignore file.
=> exercism/dart:  Address Dart analyzer errors due to Dart 2.0 strong typing

.gitignore
@exercism/dart @amscotti 
Are there any other IDE files/folders we could ignore to make it easier for you?
=> .gitignore: Add rule to exclude IDE files/folder

config.json, exercises/resistor-color/README.md, exercises/resistor-color/analysis_options.yaml, exercises/resistor-color/lib/example.dart, exercises/resistor-color/lib/resistor_color.dart, exercises/resistor-color/pubspec.yaml, exercises/resistor-color/test/resistor_color_test.dart
Hi, this PR is to add a new exercise for `resistor-color`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color)
Thanks! :)
=> Adds resistor-color exercise

config.json, exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/analysis_options.yaml, exercises/resistor-color-duo/lib/example.dart, exercises/resistor-color-duo/lib/resistor_color_duo.dart, exercises/resistor-color-duo/pubspec.yaml, exercises/resistor-color-duo/test/resistor_color_duo_test.dart
Hi, this PR is to add a new exercise for `resistor-color-duo`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/resistor-color-duo)
Thanks! :)
=> Adds resistor-color-duo exercise

config.json, exercises/binary-search-tree/README.md, exercises/binary-search-tree/analysis_options.yaml, exercises/binary-search-tree/lib/binary_search_tree.dart, exercises/binary-search-tree/lib/example.dart, exercises/binary-search-tree/pubspec.yaml, exercises/binary-search-tree/test/binary_search_tree_test.dart
This is work based off what @devkabiir has done in PR #54, the only changes are rebasing off of master and updating the formatting of `binary_search_tree_test.dart` using `bin/presubmit.dart` tool. I don't want to step on any ones toe's, but I see there is a deadline for the New Batch of Exercises milestone set for April 30th and figured I could help. 
More then happy to close this PR in favor of @devkabiir's PR if work is still being done on it.
=> Binary search tree updates

bin/create_exercise.dart
Creates a `.meta/version` file when generating a new exercise to address https://github.com/exercism/dart/issues/198. Here's a screenshot using the `create_exercise` script to generate the **bowling** exercise. 
The current version of the **bowling** exercise is `1.2.0` according to the [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/canonical-data.json) file.
=> Create '.meta/version' file from canonical.json

bin/create_exercise.dart, pubspec.lock, pubspec.yaml, test/create_exercise_test.dart, test/exercises_test.dart
The create_exercise script needed to be updated to handle a few things:
=> Update create exercise to handle more scenarios

exercises/gigasecond/README.md, exercises/gigasecond/pubspec.yaml, exercises/gigasecond/test/gigasecond_test.dart
Used the updated create_exercise to review gigasecond and add the version to pubspec.yaml
=> gigasecond: Revise exercise with updates to the specification

bin/create_exercise.dart
I went to re-generate an exercise and came to realize that the create_exercise looks for the exercise version in `.meta/version` instead of in the pubspec.yaml file.
I missed updating that section after reworking it in #170 .
=> create_exercise: Check for the version in the proper file

config/maintainers.json
@SuperPaintman hasn't contributed since I got involved in this project and @fwip contibuted since 2017.
So I suggest we set their maintainer status as alumni. I'm not exactly sure what the implications are, but overall I believe it means they moved on from the project. @iHiD correct me if I'm wrong.
=> Set inactive maintainers as alumni

bin/check_formatting.dart, bin/presubmit.dart, lib/src/utils.dart, test/exercises_test.dart
Add another argument to the check_formatting's use of dart_style. The `-i` argument defines the number of spaces to have for leading indentations.
Additionally, I took the opportunity to format the bin, lib, and test files using [dart_style's `--fix` argument](https://github.com/dart-lang/dart_style/blob/master/bin/format.dart#L40) which applies all the style fixes such as dropping use of `new` and `const` keywords and other small details.
This will help ensure our code's style is idiomatic. As the exercises are updated, I'll format them with the `--fix` argument so that we don't have one PR that formats everything.
=> Update check_formatting with new format option

exercises/anagram/README.md, exercises/anagram/lib/example.dart, exercises/anagram/pubspec.yaml, exercises/anagram/test/anagram_test.dart
Per #210, ran create_exercise to update anagram and add the version to pubspec.yaml
=> anagram: Revise exercise with updates to the specification

exercises/resistor-color/pubspec.yaml, exercises/resistor-color/test/resistor_color_test.dart
Per #210, ran create_exercise to update resistor-color and add the version to pubspec.yaml
=> resistor-color: Revise exercise with updates to the specification

exercises/resistor-color-duo/README.md, exercises/resistor-color-duo/lib/example.dart, exercises/resistor-color-duo/pubspec.yaml, exercises/resistor-color-duo/test/resistor_color_duo_test.dart
Per #210, ran create_exercise to update resistor-color-duo and add the version to pubspec.yaml
=> resistor-color-duo: Revise exercise with updates to the specification

exercises/space-age/README.md, exercises/space-age/lib/example.dart, exercises/space-age/pubspec.yaml, exercises/space-age/test/space_age_test.dart
Per #210, ran create_exercise to update space-age and add the version to pubspec.yaml
=> space-age: Update exercise with version and other updates

exercises/isbn-verifier/README.md, exercises/isbn-verifier/pubspec.yaml, exercises/isbn-verifier/test/isbn_verifier_test.dart
Per #210, ran create_exercise to update isbn-verifier and add the version to pubspec.yaml
=> isbn-verifier: Revise exercise with updates to the specification

exercises/triangle/test/triangle_test.dart
Updates the triangle example for #210 
The examples have stayed the same in the problem-specifications repository, but the test cases in the `canonical-data.json` seem to specify the input as an array of numbers. Looking through the git history, it appears that this exercise in the dart track originally implemented the methods to take 3 `num` parameters instead of an array, even though the canonical-data always specified an array. I decided to keep this for now since it seems like a better interface for methods about triangles. 
It also appears that the `version` was removed from this exercise in the problem specifications and the `create-exercise` script attempts to add `version: null` to the `pubspec.yml`. I removed this since it didn't seem helpful, but I can add it back if that is …
=> Bump triangle example

exercises/acronym/pubspec.yaml, exercises/allergies/pubspec.yaml, exercises/anagram/pubspec.yaml, exercises/armstrong-numbers/pubspec.yaml, exercises/beer-song/pubspec.yaml, exercises/binary-search-tree/pubspec.yaml, exercises/bob/pubspec.yaml, exercises/difference-of-squares/pubspec.yaml, exercises/gigasecond/pubspec.yaml, exercises/hamming/pubspec.yaml, exercises/hello-world/pubspec.yaml, exercises/isbn-verifier/pubspec.yaml, exercises/leap/pubspec.yaml, exercises/pascals-triangle/pubspec.yaml, exercises/phone-number/pubspec.yaml, exercises/raindrops/pubspec.yaml, exercises/resistor-color-duo/pubspec.yaml, exercises/resistor-color/pubspec.yaml, exercises/reverse-string/pubspec.yaml, exercises/rna-transcription/pubspec.yaml, exercises/robot-simulator/pubspec.yaml, exercises/scrabble-score/pubspec.yaml, exercises/space-age/pubspec.yaml, exercises/two-fer/pubspec.yaml, exercises/word-count/pubspec.yaml
With the move away from versions for problem specs and towards uuids for each test case, we need to remove the existing version parameters.
=> Remove version parameter all pubspec.yaml for exercises

bin/create_exercise.dart, lib/src/utils.dart, test/create_exercise_test.dart, test/exercises_test.dart
The analyzer was throwing an error for using dynamic in a for loop. So I replaced it with a cast to a Map object.
Additionally, I fixed a minor linting issue related to sorting constructors at the top of a class.
=> Fix analyzer errors

.gitignore, CONTRIBUTING.md, bin/fetch-canonical_data_syncer, bin/fetch-canonical_data_syncer.ps1
Adding a tool to allow contributors to fetch the newest tool for helping tracks keep their exercise-specific tests.toml files in sync with the latest canonical data in the problem-specifications repo.
=> Add fetch canonical data syncer

.github/workflows/test.yml
* Added `matrix` with `latest` and `dev` tags
* Disabled `fail-fast` for now
Closes #270
=> Pin CI to latest stable Dart `2.10` & prepare for NNBD

exercises/concept/futures/pubspec.yaml, exercises/concept/numbers/pubspec.yaml, exercises/concept/strings/pubspec.yaml, pubspec.lock, pubspec.yaml
dart_style was finally updated to depend on 2.12 of Dart. This PR updates our dependency and drops dart_style from the concept exercises since dart_style is only needed in our root pubspec.yaml for linting and CI
=> Bump dart style

concepts/callbacks/.meta/config.json, concepts/errors-basic/.meta/config.json, concepts/futures/.meta/config.json, concepts/iterables-basic/.meta/config.json, concepts/numbers-basic/.meta/config.json, concepts/recursion/.meta/config.json, concepts/strings-basic/.meta/config.json, concepts/type-conversion/.meta/config.json, config.json
_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._
---
To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.
See https://github.com/exercism/docs/pull/96/files for the update to the specification.
This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:
- A `blurb` key, which value is copied from the `config.json` file and subsequently removed …
=> 🤖 Add .meta/config.json file for concepts

config.json
We've had some issues getting the test runner to consistently finish running within the allotted time. Until those issues are fixed, let's disable the test runner.
=> Disable test runner

docs/ABOUT.md
The last remaining links to dartlang.org have been removed by linking to
either GitHub or pub.dev.
I have found no other mentions of dartlang.org other than in the `pubspec.lock` which is auto-generated.
This PR fixes #364
=> Remove remaining links to dartlang.org

README.md, docs/INSTALLATION.md, docs/LEARNING.md, docs/RESOURCES.md, docs/TESTS.md
The PR is releated to Issue #343 
- Fix Test tag on readme;
- Fix link of repositories who changed the master branch to main;
- Fix broken link to OSX PATH configuration;
- Fix links to hello-world exercise;
=> fixing broken links and readme tag

.github/workflows/links.yml, config.json, exercises/practice/forth/.docs/instructions.md, exercises/practice/forth/.meta/config.json, exercises/practice/forth/.meta/lib/example.dart, exercises/practice/forth/analysis_options.yaml, exercises/practice/forth/lib/forth.dart, exercises/practice/forth/pubspec.yaml, exercises/practice/forth/test/forth_test.dart
Hope it will be first 'hard' task.
=> contributing translation of js's track 'forth' excersize.

exercises/practice/forth/test/forth_test.dart
Following the pattern found on other exercises, adding `true` to the `skip` parameter on `test` function allows the practitioner to run more tests incrementally.
=> Adding the instruction to skip tests on Forth exercise

exercises/practice/space-age/.docs/instructions.md, exercises/practice/space-age/.meta/config.json, exercises/practice/space-age/.meta/tests.toml
This updates the space-age exercise with changes
in the problem-specifications repository.
The instructions were updated with formatting changes.
The metadata updated a link to HTTP (rather than HTTPS) since the HTTPS version of the link doesn't work.
There was one additional test, that added an error case (invalid planet).
This exercise did not previously introduce error handling. It seems to me that error handling doesn't make the exercise more interesting. Also I think that keeping the exercises as simple as possible at the start is beneficial, and since there are other exercises that do introduce error handling, I don't think that the student misses out in the long run.
As such I chose not to bring the new test in here.
=> Sync space-age with problem-specifications

exercises/practice/acronym/.meta/config.json, exercises/practice/beer-song/.meta/config.json, exercises/practice/bob/.meta/config.json, exercises/practice/darts/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/minesweeper/.meta/config.json, exercises/practice/nth-prime/.meta/config.json, exercises/practice/pascals-triangle/.meta/config.json, exercises/practice/resistor-color/.meta/config.json, exercises/practice/reverse-string/.meta/config.json, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/two-fer/.meta/config.json
This runs
bin/configlet sync --update --metadata --exercise SLUG
on any exercises that don't require any changes to their test suites in order to get up to date with the problem-specifications repository.
I generally prefer to update one exercise at a time, but reviewing gets quite tedious when there are lots of small updates, so I went with a bulk update here.
=> Sync metadata for practice exercises

exercises/practice/allergies/.docs/instructions.md, exercises/practice/allergies/.meta/config.json, exercises/practice/allergies/.meta/tests.toml, exercises/practice/allergies/test/allergies_test.dart
This puts all the tests in the same group rather than
grouping them per the canonical-data.json structure in
problem-specifications.
In order to help make the logical groupings apparent,
the test names have been updated to be prefixed with the
group description.
To make it as easy as possible to review, I've indented
the tests two spaces extra in the first commit, and then
fixed the indentation in the second commit.
In the third commit I've synced the allergies exercise by running 
```
bin/configlet sync --update --exercise allergies
```
This brought in updated instructions and an extra test.
=> Sync allergies with problem-specifications

exercises/practice/darts/.docs/instructions.md, exercises/practice/diamond/.docs/instructions.md, exercises/practice/hello-world/.docs/instructions.md, exercises/practice/leap/.docs/instructions.md, exercises/practice/pig-latin/.docs/instructions.md, exercises/practice/rna-transcription/.docs/instructions.md, exercises/practice/space-age/.docs/instructions.md
This syncs the instructions for exercises that
do not have pending test changes.
The update ensures that urls use https rather than http, and
that unordered lists use a hyphen.
=> Sync docs with problem-specifications

exercises/practice/allergies/.meta/config.json, exercises/practice/beer-song/.meta/config.json, exercises/practice/bob/.meta/config.json, exercises/practice/diamond/.meta/config.json, exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/hello-world/.meta/config.json, exercises/practice/leap/.meta/config.json, exercises/practice/nth-prime/.meta/config.json, exercises/practice/pascals-triangle/.meta/config.json, exercises/practice/rna-transcription/.meta/config.json, exercises/practice/secret-handshake/.meta/config.json, exercises/practice/space-age/.meta/config.json
This syncs metadata for those exercises that do not have
pending changes to the tests.
This brings in updated URLs to ensure that they use
https rather than http.
=> Sync metadata with problem-specifications

exercises/practice/anagram/.docs/instructions.md, exercises/practice/anagram/.meta/config.json, exercises/practice/anagram/.meta/tests.toml, exercises/practice/anagram/analysis_options.yaml, exercises/practice/anagram/test/anagram_test.dart
- Regenerate anagram (Note that this exercise does not have groups in the canonical data.)
- Sync anagram with problem-specifications
=> Sync anagram with problem-specifications

exercises/practice/collatz-conjecture/.docs/instructions.md, exercises/practice/collatz-conjecture/.meta/config.json, exercises/practice/collatz-conjecture/.meta/lib/example.dart, exercises/practice/collatz-conjecture/.meta/tests.toml, exercises/practice/collatz-conjecture/test/collatz_conjecture_test.dart
This regenerate collatz-conjecture, and then syncs with problem-specifications.
The sync brought in updated instructions and
reimplemented test cases. The test cases changed the
expected error message from 'number' to 'integer' which
is more correct for the collatz-conjecture (which does
not apply to floats).
This means that existing solutions will fail the tests,
but with a failure that is trivial to fix.
=> Sync collatz-conjecture with problem specifications

exercises/practice/resistor-color-duo/.docs/instructions.md, exercises/practice/resistor-color-duo/.meta/config.json, exercises/practice/resistor-color-duo/.meta/tests.toml, exercises/practice/resistor-color-duo/test/resistor_color_duo_test.dart
- Regenerate resistor-color-duo in first commit to minimize diff when syncing
- Sync resistor-color-duo with problem-specifications
This brings in improved documentation and a couple of new tests.
It also removes the explicit type when assigning 'result' in the tests.
=>  Sync resistor-color-duo with problem-specifications

exercises/practice/allergies/test/allergies_test.dart, exercises/practice/anagram/test/anagram_test.dart, exercises/practice/collatz-conjecture/test/collatz_conjecture_test.dart, exercises/practice/hamming/test/hamming_test.dart, exercises/practice/isbn-verifier/test/isbn_verifier_test.dart, exercises/practice/isogram/test/isogram_test.dart
Per #426, drop types for variable definitions when assigning
results in test suites.
This removes type definitions for test suites that have
been synced with problem-specifications recently.
=> Remove explicit type definitions

exercises/practice/pangram/.docs/instructions.md, exercises/practice/pangram/.meta/config.json, exercises/practice/pangram/.meta/tests.toml, exercises/practice/pangram/test/pangram_test.dart
The first commit manually switches the existing pangram test suite to use single-quoted strings for the test descriptions, to help minimize the diff upon regenerating the test suite.
The second commit regenerates the test suite with the existing tests, to minimize the diff upon syncing with problem-specifications.
The third commit finally syncs with the upstream specification.
=> Sync pangram with problem-specifications

exercises/practice/word-count/.docs/instructions.md, exercises/practice/word-count/.meta/config.json, exercises/practice/word-count/.meta/lib/example.dart, exercises/practice/word-count/.meta/tests.toml, exercises/practice/word-count/test/word_count_test.dart
The first commit regenerates the word-count exercise based on the previously selected test cases, in order to minimize the diff when syncing.
Note that the problem-specification did not group the tests, so regenerating it removed the manually-created grouping.
The second commit syncs with problem-specifications. This brought in two new tests. The example solution had to be tweaked to pass the updated test suite.
<details>
<summary>Failed test</summary>
```
00:00 +8: test/word_count_test.dart: WordCount with apostrophes                                                                                                   00:00 +8 -1: test/word_count_test.dart: WordCount with apostrophes [E] …
```
=> Sync word-count with problem-specifications

exercises/practice/luhn/.docs/instructions.md, exercises/practice/luhn/.meta/config.json, exercises/practice/luhn/.meta/tests.toml, exercises/practice/luhn/test/luhn_test.dart
The first commit manually updates strings to use single-quotes rather than double-quotes, in order to minimize the diff when regenerating. The second commit regenerates the test suite based on the existing `tests.toml` file, which surprisingly added new tests. The third commit syncs with problem-specifications, which adds even more tests. None of the tests had any surprises, though; just more edge cases. The existing example solution didn't need to be updated at all.
=> Sync luhn from problem-specifications

exercises/practice/phone-number/.docs/instructions.md, exercises/practice/phone-number/.meta/config.json, exercises/practice/phone-number/.meta/tests.toml, exercises/practice/phone-number/test/phone_number_test.dart
The first commit regenerates the test suite. This removed nesting, which I believe was done manually.
The second commit syncs with problem-specifications, updating the instructions and reimplementing two tests to get less ambiguous error situations.
=> Sync phone-number with problem-specifications

exercises/practice/gigasecond/.docs/instructions.md, exercises/practice/gigasecond/.meta/config.json, exercises/practice/gigasecond/.meta/lib/example.dart, exercises/practice/gigasecond/.meta/tests.toml, exercises/practice/gigasecond/test/gigasecond_test.dart
The first commit regenerates the test suite. I decided to remove the three first tests, as they are all redundant,
keeping only the two that are specified in the problem-specifications
using full datetimes as opposed to just dates.
The second commit syncs with problem-specifications. The sync updated the instructions.
There was an additional test that I chose not to include, as it
is a test for immutability, but as far as I can tell, the Dart
DateTime type is immutable already, so the test doesn't make
sense here.
=> Sync gigasecond with problem-specifications

config.json, exercises/practice/armstrong-numbers/.docs/instructions.md, exercises/practice/armstrong-numbers/.meta/config.json, exercises/practice/armstrong-numbers/.meta/lib/example.dart, exercises/practice/armstrong-numbers/.meta/tests.toml, exercises/practice/armstrong-numbers/test/armstrong_numbers_test.dart
This updates the instructions and brings in two new tests,
both of which handle very big numbers.
In order to support these new tests, the example solution
has been updated to use BigInt.
Closes #434
=> Sync armstrong-numbers with problem-specifications

exercises/practice/difference-of-squares/.meta/config.json, exercises/practice/difference-of-squares/test/difference_of_squares_test.dart
This allows types to be inferred in the test suite
for difference-of-squares instead of explicitly defining
them.
It also removes a level of nesting by moving the group definitions
out of main.
=> Simplify assignment in difference-of-squares

exercises/practice/scrabble-score/.meta/config.json, exercises/practice/scrabble-score/test/scrabble_score_test.dart
This remove the explicit type definition in the
variable assignment in the scrabble-score test suite
=> Simplify assignments in scrabble-score

exercises/practice/two-fer/.meta/config.json, exercises/practice/two-fer/test/two_fer_test.dart
Remove the explicit type definition in two-fer test suite,
allowing the type to be inferred.
=> Simplify assignment in two-fer

exercises/practice/space-age/.meta/config.json, exercises/practice/space-age/test/space_age_test.dart
This removes the explicit assignments in space-age,
=> Simplify assignment in space-age

exercises/practice/raindrops/.meta/config.json, exercises/practice/raindrops/test/raindrops_test.dart
This removes the explicit assignments in raindrops,
=> Simplify assignment in raindrops

exercises/practice/rna-transcription/.meta/config.json, exercises/practice/rna-transcription/test/rna_transcription_test.dart
This removes the explicit assignments in rna-transcription,
=> Simplify assignment in rna-transcription

exercises/practice/reverse-string/.meta/config.json, exercises/practice/reverse-string/test/reverse_string_test.dart
This removes the explicit assignments in reverse-string,
=> Simplify assignment in reverse-string

exercises/practice/nth-prime/.meta/config.json, exercises/practice/nth-prime/test/nth_prime_test.dart
This removes the explicit assignments in nth-prime,
=> Simplify assignment in nth-prime

exercises/practice/darts/.meta/config.json, exercises/practice/darts/test/darts_test.dart
This removes the explicit assignments in darts,
=> Simplify assignment in darts

exercises/practice/acronym/.meta/config.json, exercises/practice/acronym/test/acronym_test.dart
This removes the explicit assignments in acronym,
=> Simplify assignment in acronym

exercises/practice/diamond/.meta/config.json, exercises/practice/diamond/test/diamond_test.dart
This removes the explicit assignments in diamond,
=> Simplify assignment in diamond

exercises/practice/robot-simulator/.meta/config.json, exercises/practice/robot-simulator/test/robot_simulator_test.dart
This regenerates the test suite for robot-simulator.
In doing so it:
- removes the explicit type when assigning the robot
- moves the custom expected() definition to the top of the file
- moves the group definitions out of main
I'm not sure if moving the expected() definition violates dart
style. In the generator I have custom initialization at the top,
and this felt like it was basically the same thing, so I didn't
introduce another way of customizing.
If you have strong feelings about it, I can change it.
=> Regenerate robot-simulator

exercises/practice/minesweeper/.meta/config.json, exercises/practice/minesweeper/.meta/lib/example.dart, exercises/practice/minesweeper/test/minesweeper_test.dart
This:
- fixes a typo in a getter name (annoted -> annotated)
- replaces multiple test groups with a single group
- remove explicit type definition when assigning 'result'
- makes the 'result' assignment final
=> Regenerate minesweeper test suite

exercises/practice/secret-handshake/.meta/config.json, exercises/practice/secret-handshake/test/secret_handshake_test.dart
This removes the explicit assignments in secret-handshake,
=> Simplify assignment in secret-handshake

exercises/practice/allergies/test/allergies_test.dart
The group description in the allergies test suite
was using double-quotes to delimit the strings.
This replaces the double-quoted strings with
single-quoted strings.
=> Fix string syntax in allergies tests

exercises/practice/bob/test/bob_test.dart
This removes the explicit assignments in bob,
=> Simplify assignment in bob

exercises/practice/pascals-triangle/.meta/config.json, exercises/practice/pascals-triangle/test/pascals_triangle_test.dart
This removes the explicit assignments in pascals-triangle,
=> Simplify assignment in pascals-triangle

.github/workflows/test.yml
We should include the Dart analyzer when we run the workflow. Though it only checks the bin, lib, and test folders because the exercises can't be checked. The exercises would throw errors because they are referencing a file that does not have the expected implementations.
=> Add dart analyzer to Test workflow

config.json, exercises/practice/sum-of-multiples/.docs/instructions.md, exercises/practice/sum-of-multiples/.meta/config.json, exercises/practice/sum-of-multiples/.meta/lib/example.dart, exercises/practice/sum-of-multiples/.meta/tests.toml, exercises/practice/sum-of-multiples/analysis_options.yaml, exercises/practice/sum-of-multiples/lib/sum_of_multiples.dart, exercises/practice/sum-of-multiples/pubspec.yaml, exercises/practice/sum-of-multiples/test/sum_of_multiples_test.dart
This is a proposal for a new exercise based on the canonical data in the problem-specifications repository.
I didn't make any design choices whatsoever—if you think a different API would be better suited to this exercise, please suggest some changes, and I will regenerate the test suite.
I put myself as contributor rather than author, since I don't intend to write the example solution.
As such, the authorship of this exercise is up for grabs to anyone who wants to spend a few minutes writing some code that will pass the tests.
=> Add stub for new exercise: sum-of-multiples

exercises/practice/pig-latin/.meta/config.json
The fmt command removed a custom key.
This is a bug in configlet, and I'll be opening an issue
in the configlet repo to ensure that it doesn't happen in the future.
=> Revert configlet fmt for pig-latin

.github/workflows/links.yml, .github/workflows/test.yml
This PR updates GitHub Actions runners to a specific version.
This ensures that the workflow will always run on the same runner, which makes your build _stable_.
The PR updates the *-latest version with the current version, as specified in https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-test-runners-to-version for more information.
=> CI: pin GitHub Actions runners

.github/workflows/links.yml
This PR updates GitHub Actions workflows to a specific version.
This ensures that the workflow will always run the same code, which makes your build _stable_.
It will also prevent a potential security issue where a tag could be replaced by a malicious commit without consumers being aware of it.
The PR updates each non-SHA based workflow reference with the SHA of the referenced version/tag, so the current behavior should not change.
See https://exercism.org/docs/building/github/gha-best-practices#h-pin-actions-to-shas for more information.
=> CI: pin GitHub Actions workflows

config.json
I forgot to do this in #533.
Now new exercises (via `configlet create`) should get the invalidator file in the exercise config.
=> Add the invalidator to the track config

exercises/practice/yacht/lib/categories.dart
https://forum.exercism.org/t/yacht-the-order-of-threes-fours-in-enum-category/10931
=> yacht: fix enum order

.github/workflows/analyze-code.yml, .github/workflows/format-check.yml
Addresses #591
Separating the Format Check and Code Analyzing into separate actions.
In a future PR, we can look at trying to get more details into the Format job's logs to know which files were not formatted.
=> Separate format check and analyzer code into new actions

exercises/practice/game-of-life/test/game_of_life_test.dart
http://forum.exercism.org/t/well-defined-input-and-output-requirements-in-exercises/17809/12
No need to re-run tests here.
=> Rename `game-of-life` inputs
