config.json

See the discussion https://github.com/exercism/discussions/issues/161

Rename the track for the sake of consistency

---

README.md

We've updated this to take a subcommand.

Fix incorrect configlet command in README

---

docs/INSTALLATION.md

Thank you for this PR! :tada:
When we review your submission we will check the following:

Instructions for installation

---

docs/LEARNING.md
docs/RESOURCES.md

Thank you for this PR! :tada:
When we review your submission we will check the following:

Info for Resources and Learning pages

---

docs/EXERCISE_README_INSERT.md

Exercise Insert Info

---

docs/TESTS.md

Tests page information

---

docs/TESTS.md

As reported in #22, I am trying to provide a workaround.
Since it seems the code blocks are causing the issue I am going to try some alternatives
I will test these in a jekyll page since this seems to be related to red-carpet, we otherwise won't know how the webpage would turn out.

Fix numbering issue with Markdown as reported

---

exercises/difference-of-squares/test/difference_of_squares_test.dart
exercises/rna-transcription/test/rna_transcription_test.dart

Skip non-first tests for some exercises

---

tool/create-exercise

Now consistent with existing tests.

For create-exercise tool, update test version to '<0.13.0'

---

config/maintainers.json
pubspec.yaml

@fwip @kabiir 
Would you like to be maintainers for this repo?
You both have done a terrific job and done a lot more than I could hope for. **Thank you**
There are no requirements in terms of amount of time spent or work done. Just whenever you can.
Plus, you can approve and then merge in PRs.
Just don't push directly to master any changes. We want anything big or small to be a PR.

Update Maintainer JSON

---

exercises/anagram/README.md
exercises/bob/README.md
exercises/difference-of-squares/README.md
exercises/gigasecond/README.md
exercises/hamming/README.md
exercises/hello-world/README.md
exercises/leap/README.md
exercises/raindrops/README.md
exercises/rna-transcription/README.md
exercises/word-count/README.md

Decided to run the `configlet generate` command on all the exercises and voila!
Most were missing a section on how to run tests. So included those updates here as well as added a README for raindrops which was apparently missing one.

Revise Exercise READMEs using configlet generate command

---

exercises/leap/test/leap_test.dart

Closes #64 
Addresses a loophole that was fixed in the specification.

Address loophole in Leap test case Closes #64

---

exercises/anagram/pubspec.lock
exercises/bob/pubspec.lock
exercises/difference-of-squares/pubspec.lock
exercises/gigasecond/pubspec.lock
exercises/hamming/pubspec.lock
exercises/hello-world/pubspec.lock
exercises/leap/pubspec.lock
exercises/phone-number/pubspec.lock
exercises/raindrops/pubspec.lock
exercises/rna-transcription/pubspec.lock
exercises/word-count/pubspec.lock
pubspec.lock

Bumping the dependencies across the board to ensure they are all up to date.

Bump pubspec dependencies

---

README.md

I felt the Setup section was a bit lacking so I added a few helpful states regarding setting up the project.

Provide some helpful statements in Setup

---

CONTRIBUTING.md

The intent is to update Contributing so it's clear to any future contributors

Update CONTRIBUTING with some minor fixes

---

config.json
config/maintainers.json

The formatting resolved a possible unicode issue and corrected the formatting within config.json

Use `configlet fmt .` to format maintainers.json and config.json

---

CONTRIBUTING.md
docs/EXERCISE_README_INSERT.md
docs/INSTALLATION.md

@fwip @kabiir @raphalvessa I would appreciate some feedback on the docs cause I wrote most of them, if not all, and they could use some fresh eyes.

Minor changes to update docs for track page

---

config.json

@exercism/dart With all the issues in [Polish Up Milestone](https://github.com/exercism/dart/milestone/2), it seems Launch #1 is ready to go!
Upon merging of this PR, the Dart Track will no longer be under the Upcoming section, but will be listed as a normal ready for use track.
Once this PR is merged, I'll also close the Polish Up milestone. I think we have a few PRs listed as low-priority that we can move up. I'd like get all the new exercises done and wrap up the presubmit-scripts.

Launch Track

---

bin/create_exercise.dart
pubspec.lock
pubspec.yaml

Revise create-exercise script to handle new schema policy

---

config.json

config: Remove unlocked_by values for core exercises

---

config.json
exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/lib/armstrong_numbers.dart
exercises/armstrong-numbers/lib/example.dart
exercises/armstrong-numbers/pubspec.yaml
exercises/armstrong-numbers/test/armstrong_numbers_test.dart

Add new exercise based on [this specification](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers)
@exercism/dart

New Exercise: Armstrong numbers

---

config.json
exercises/scrabble-score/README.md
exercises/scrabble-score/lib/example.dart
exercises/scrabble-score/lib/scrabble_score.dart
exercises/scrabble-score/pubspec.yaml
exercises/scrabble-score/test/scrabble_score_test.dart
test/exercises_test.dart

I haven't actually ran the presubmit and formatter check on this code yet. Just getting this out there for review.

New Exercise: Scrabble Score

---

README.md

readme: add missing lang to code block

---

docs/ABOUT.md

#127 has sub-bullets that mention the About page being refined.
I've added a little more information to this page that was missing. Please provide feedback if possible.
cc: @Stargator @kytrinyx

Minor edits to About page in preparation for V2

---

.travis.yml
bin/check_formatting.dart
test/exercises_test.dart

Going to see if a PR into exercism's repo will work better than mine.

#120 ensure failures for formatting and tests

---

config/maintainers.json
pubspec.yaml

* Also, correct pubspec.yaml with username change for kabiir to devkabiir
@jvarness has expressed interest in being a maintainer and seems to have a good grasp of the track's goals and intent.

exercism/dart: Add jvarness as a maintainer

---

config.json

Putting the finishing touches on #127 so that we're ready for the V2 launch that happened a few weeks ago 😆

Provide non-empty description for Dart track.

---

config.json
exercises/diamond/README.md
exercises/diamond/analysis_options.yaml
exercises/diamond/lib/diamond.dart
exercises/diamond/lib/example.dart
exercises/diamond/pubspec.yaml
exercises/diamond/test/diamond_test.dart

[Rihanna - Diamond](https://www.youtube.com/watch?v=lWA2pjMjpBs)

New Exercise: diamond

---

README.md

Update setup requirements in README

---

exercises/anagram/test/anagram_test.dart

This exercise had a few changes in 2018 with the revision of an existing test

anagram: Revise exercise with updates to the specification

---

exercises/acronym/README.md
exercises/acronym/lib/example.dart
exercises/acronym/test/acronym_test.dart

This exercise had a few changes in 2018 with the inclusion of three new tests and a modification to the README.

acronym: Revise exercise with updates to the specification

---

config.json
exercises/pascals-triangle/README.md
exercises/pascals-triangle/analysis_options.yaml
exercises/pascals-triangle/lib/example.dart
exercises/pascals-triangle/lib/pascals_triangle.dart
exercises/pascals-triangle/pubspec.yaml
exercises/pascals-triangle/test/pascals_triangle_test.dart

New Exercise: Pascal's Triangle

---

config.json
exercises/isogram/README.md
exercises/isogram/analysis_options.yaml
exercises/isogram/lib/example.dart
exercises/isogram/lib/isogram.dart
exercises/isogram/pubspec.yaml
exercises/isogram/test/isogram_test.dart

I tried thinking of a phrase to put here that's an isogram but it's actually really hard.

New Exercise: isogram

---

config.json
exercises/darts/README.md
exercises/darts/analysis_options.yaml
exercises/darts/lib/darts.dart
exercises/darts/lib/example.dart
exercises/darts/pubspec.yaml
exercises/darts/test/darts_test.dart

Hi, this PR is to adds a new exercise for `darts`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/darts)
I'm still learning Dart, so feel free to point out anything that needs to be change or improved.
Thanks! :)

Adds darts exercise

---

config.json
exercises/pangram/README.md
exercises/pangram/analysis_options.yaml
exercises/pangram/lib/example.dart
exercises/pangram/lib/pangram.dart
exercises/pangram/pubspec.yaml
exercises/pangram/test/pangram_test.dart

Hi, this PR is to add a new exercise for `pangram`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/pangram)
This is one of the exercises on the list in issue #149
I'm still learning Dart, so feel free to point out anything that needs to be change or improved.
One note, this may need to be rebased if #172 is merged due to conflicts in the `config.json` file.
Thanks! :)

Adds pangram exercise

---

exercises/armstrong-numbers/README.md
exercises/armstrong-numbers/test/armstrong_numbers_test.dart

Armstrong-numbers had an update to the README. Made some minor adjustments in the test suite.

armstrong-numbers: Revise exercise with updates to the specification

---

config.json
exercises/two-fer/.meta/canonical-data.json
exercises/two-fer/README.md
exercises/two-fer/analysis_options.yaml
exercises/two-fer/lib/example.dart
exercises/two-fer/lib/two_fer.dart
exercises/two-fer/pubspec.yaml
exercises/two-fer/test/two_fer_test.dart

Hi, this PR is to add a new exercise for `two-fer`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/two-fer)
I'm still learning Dart, so feel free to point out anything that needs to be change or improved.
Thanks! :)

Adds two-fer exercise

---

config.json
exercises/reverse-string/README.md
exercises/reverse-string/analysis_options.yaml
exercises/reverse-string/lib/example.dart
exercises/reverse-string/lib/reverse_string.dart
exercises/reverse-string/pubspec.yaml
exercises/reverse-string/test/reverse_string_test.dart

Hi, this PR is to add a new exercise for `reverse-string`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/reverse-string)
Thanks! :)

Adds reverse-string exercise

---

config.json
exercises/luhn/README.md
exercises/luhn/analysis_options.yaml
exercises/luhn/lib/example.dart
exercises/luhn/lib/luhn.dart
exercises/luhn/pubspec.yaml
exercises/luhn/test/luhn_test.dart

Hi, this PR is to add a new exercise for `luhn`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/luhn)
This is one of the exercises on the list in issue #149 
I'm still learning Dart, so feel free to point out anything that needs to be change or improved.
Thanks! :)

Adds luhn exercise

---

config.json
exercises/isbn-verifier/README.md
exercises/isbn-verifier/analysis_options.yaml
exercises/isbn-verifier/lib/example.dart
exercises/isbn-verifier/lib/isbn_verifier.dart
exercises/isbn-verifier/pubspec.yaml
exercises/isbn-verifier/test/isbn_verifier_test.dart

Hi, this PR is to add a new exercise for `isbn-verifier`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/isbn-verifier)
Thanks! :)

Adds isbn-verifier exercise

---

config.json
exercises/collatz-conjecture/README.md
exercises/collatz-conjecture/analysis_options.yaml
exercises/collatz-conjecture/lib/collatz_conjecture.dart
exercises/collatz-conjecture/lib/example.dart
exercises/collatz-conjecture/pubspec.yaml
exercises/collatz-conjecture/test/collatz_conjecture_test.dart

Hi, this PR is to add a new exercise for `collatz-conjecture`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/collatz-conjecture)
Thanks! :)

Adds collatz-conjecture exercise

---

config.json
exercises/prime-factors/README.md
exercises/prime-factors/analysis_options.yaml
exercises/prime-factors/lib/example.dart
exercises/prime-factors/lib/prime_factors.dart
exercises/prime-factors/pubspec.yaml
exercises/prime-factors/test/prime_factors_test.dart

Hi, this PR is to add a new exercise for `prime-factors`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/prime-factors)
Thanks! :)

Adds prime-factors exercise

---

exercises/armstrong-numbers/test/armstrong_numbers_test.dart

Hi, this PR is to update exercise for `armstrong-numbers`, with a new test case for `0`. [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers)

Updates to armstrong-numbers for v1.1.0

---

config.json
exercises/nth-prime/README.md
exercises/nth-prime/analysis_options.yaml
exercises/nth-prime/lib/example.dart
exercises/nth-prime/lib/nth_prime.dart
exercises/nth-prime/pubspec.yaml
exercises/nth-prime/test/nth_prime_test.dart

Hi, this PR is to add a new exercise for `nth-prime`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/nth-prime)
Thanks! :)

Adds nth-prime exercise

---

config.json
exercises/allergies/README.md
exercises/allergies/analysis_options.yaml
exercises/allergies/lib/allergies.dart
exercises/allergies/lib/example.dart
exercises/allergies/pubspec.yaml
exercises/allergies/test/allergies_test.dart

Hi, this PR is to add a new exercise for `allergies`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/allergies)
Thanks! :)

Adds allergies exercise

---

config.json
exercises/triangle/README.md
exercises/triangle/analysis_options.yaml
exercises/triangle/lib/example.dart
exercises/triangle/lib/triangle.dart
exercises/triangle/pubspec.yaml
exercises/triangle/test/triangle_test.dart
test/exercises_test.dart

Hi, this PR is to add a new exercise for `triangle`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/triangle)
Thanks! :)

Adds triangle exercise

---

config.json
exercises/secret-handshake/README.md
exercises/secret-handshake/analysis_options.yaml
exercises/secret-handshake/lib/example.dart
exercises/secret-handshake/lib/secret_handshake.dart
exercises/secret-handshake/pubspec.yaml
exercises/secret-handshake/test/secret_handshake_test.dart

Hi, this PR is to add a new exercise for `secret-handshake`, [here is a link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/secret-handshake)
Thanks! :)

Adds secret-handshake exercise

---

config.json

Closes #197
Note: A suitable replacement for `unicode` topic is still missing

♻refactor (config.json) Use new names for outdated topics

---

exercises/reverse-string/lib/example.dart
exercises/reverse-string/pubspec.yaml
exercises/reverse-string/test/reverse_string_test.dart

Re-ran the `create_exercise` script for the `reverse-string` exercise as a part of #210.

reverse-string: Update exercise and add version info

---

exercises/phone-number/lib/example.dart
exercises/phone-number/pubspec.yaml
exercises/phone-number/test/phone_number_test.dart

Used the updated create_exercise to review phone-number and add the version to pubspec.yaml

phone-number: Revise exercise with updates to the specification

---

exercises/raindrops/README.md
exercises/raindrops/pubspec.yaml
exercises/raindrops/test/raindrops_test.dart

Used the updated create_exercise to review raindrops and add the version to pubspec.yaml

raindrops: Revise exercise with updates to the specification

---

exercises/rna-transcription/pubspec.yaml
exercises/rna-transcription/test/rna_transcription_test.dart

Used the updated create_exercise to review rna-transcription and add the version to pubspec.yaml

rna-transcription: Revise exercise with updates to the specification

---

exercises/scrabble-score/README.md
exercises/scrabble-score/test/scrabble_score_test.dart

Used the updated create_exercise to review scrabble-score and add the version to pubspec.yaml

scrabble-score: Revise exercise with updates to the specification

---

exercises/leap/README.md
exercises/leap/pubspec.yaml
exercises/leap/test/leap_test.dart

Used the updated create_exercise to review leap and add the version to pubspec.yaml

leap: Revise exercise with updates to the specification

---

exercises/space-age/lib/space_age.dart
exercises/space-age/test/space_age_test.dart

Per #210, updated create_exercise to review space-age and add the version to pubspec.yaml

space-age: Revise exercise with updates to the specification

---

exercises/word-count/test/word_count_test.dart

Per #210, updated create_exercise to review word-count and add the version to pubspec.yaml

word-count: Revise exercise with updates to the specification

---

exercises/hamming/README.md
exercises/hamming/lib/example.dart
exercises/hamming/pubspec.yaml
exercises/hamming/test/hamming_test.dart

Used the updated create_exercise to review hamming and add the version to pubspec.yaml

hamming: Revise exercise with updates to the specification

---

exercises/two-fer/lib/example.dart
exercises/two-fer/lib/two_fer.dart
exercises/two-fer/pubspec.yaml
exercises/two-fer/test/two_fer_test.dart

Per #210, ran create_exercise to update two-fer and add the version to pubspec.yaml

two-fer: Revise exercise with updates to the specification

---

exercises/beer-song/test/beer_song_test.dart
exercises/gigasecond/lib/example.dart
exercises/gigasecond/test/gigasecond_test.dart
exercises/phone-number/lib/example.dart
exercises/rna-transcription/lib/example.dart
exercises/space-age/lib/example.dart
exercises/space-age/test/space_age_test.dart
exercises/word-count/lib/example.dart
exercises/word-count/test/word_count_test.dart

The exercises formatted in this PR were recently updated, but still used the formatting for the Dart 1.0 style.
They are now formatted to the Dart 2.0 styling (dropped use of `new` keyword)

Format recently updated exercises

---

exercises/allergies/pubspec.yaml
exercises/allergies/test/allergies_test.dart

Per #210, ran create_exercise to update allergies and add the version to pubspec.yaml

allergies: Revise exercise with updates to the specification

---

exercises/armstrong-numbers/pubspec.yaml
exercises/armstrong-numbers/test/armstrong_numbers_test.dart

Per #210, ran create_exercise to update armstrong-numbers and add the version to pubspec.yaml

armstrong-number: Revise exercise with updates to the specification

---

exercises/hello-world/pubspec.yaml
exercises/hello-world/test/hello_world_test.dart

Per #210, ran create_exercise to update hello-world and add the version to pubspec.yaml

hello_world: Revise exercise with updates to the specification

---

README.md

Related to https://github.com/exercism/dart/pull/195

Update min requirement in readme

---

exercises/bob/README.md
exercises/bob/pubspec.yaml
exercises/bob/test/bob_test.dart

Per #210, ran create_exercise to update bob and add the version to pubspec.yaml

bob: Revise exercise with updates to the specification

---

exercises/difference-of-squares/lib/example.dart
exercises/difference-of-squares/pubspec.yaml
exercises/difference-of-squares/test/difference_of_squares_test.dart

Per #210, ran create_exercise to update difference-of-squares and add the version to pubspec.yaml

difference-of-squares: Revise exercise with updates to the specification

---

exercises/scrabble-score/README.md
exercises/scrabble-score/pubspec.yaml
exercises/scrabble-score/test/scrabble_score_test.dart

Per #210, ran create_exercise to update scrabble-score and add the version to pubspec.yaml

scrabble-score: Update exercise with version and minor changes

---

exercises/word-count/README.md
exercises/word-count/pubspec.yaml
exercises/word-count/test/word_count_test.dart

Per #210, ran create_exercise to update word-count and add the version to pubspec.yaml

word-count: Update exercise with version and other updates

---

exercises/binary-search-tree/README.md
exercises/binary-search-tree/analysis_options.yaml
exercises/binary-search-tree/pubspec.yaml
exercises/binary-search-tree/test/binary_search_tree_test.dart

Per #210, ran create_exercise to update binary-search-tree and add the version to pubspec.yaml

binary-search-tree: Revise exercise with updates to the specification

---

exercises/pascals-triangle/pubspec.yaml
exercises/pascals-triangle/test/pascals_triangle_test.dart

Per #210, ran create_exercise to update pascals-triangle and add the version to pubspec.yaml

pascals-triangle: Revise exercise with updates to the specification

---

exercises/bob/lib/example.dart
exercises/bob/pubspec.yaml
exercises/bob/test/bob_test.dart

Two tests were updated in the exercise recently. So I am apply those updates from the canonical-data.json

bob: Update two tests

---

config.json
exercises/robot-simulator/README.md
exercises/robot-simulator/analysis_options.yaml
exercises/robot-simulator/lib/example.dart
exercises/robot-simulator/lib/orientation.dart
exercises/robot-simulator/lib/position.dart
exercises/robot-simulator/lib/robot_simulator.dart
exercises/robot-simulator/pubspec.yaml
exercises/robot-simulator/test/robot_simulator_test.dart

👋 
This PR is to add a new exercise for robot-simulator, here is a [link to the problem-specifications](https://github.com/exercism/problem-specifications/tree/master/exercises/robot-simulator).
I'm a Dart newbie, so feel free to point out anything that needs to be change or improved.
Thanks! 😄

Adds robot-simulator exercise

---

exercises/gigasecond/lib/gigasecond.dart

Updates the starter code of the `gigasecond` exercise to match the tests (and the example solution) as mention in #257

Change from empty class to empty function

---

exercises/minesweeper/test/minesweeper_test.dart

remove useless constructor and already tested.
for issue #252 . it's not even a bug.

#252 remove useless constructor

---

config.json
exercises/phone-number/README.md

Fixes missing code brackets (typo).

[phone-number]: Update Readme

---

exercises/diamond/test/diamond_test.dart

Bumps Diamond exercise for #210

[diamond]: Bump exercise

---

docs/TESTS.md

Hello 👋
I add some more informations about tests result (like what does `~` means, etc...).
Thanks ☺️
Issue : #246

Documentation: Adding further information about tests (e.g. skipping)

---

exercises/collatz-conjecture/test/collatz_conjecture_test.dart

collatz-conjecture: Update link to point to latest docs for package test

---

config/maintainers.json

Hey everyone,
I'm sorry for radio silence over the last... Well, it's been a very long time. I have not had the spare time to commit to being a mentor or a maintainer on Exercism. As such, I wanted to mark myself as an alum.
Do know that I'm alive and well and that I very much would like to contribute to the track again in the future (time permitting :) )

Make jvarness an alum

---

exercises/practice/hello-world/lib/hello_world.dart

Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46

🤖 Simplify `hello-world` stub

---

.github/workflows/test.yml
CONTRIBUTING.md
README.md
docs/TESTS.md
exercises/concept/futures/.docs/cli.md
exercises/concept/numbers/.docs/cli.md
exercises/concept/strings/.docs/cli.md
exercises/shared/.docs/tests.md

I noticed that many people have had problems using pub. I added a little excerpt about how `dart test` also works, and is possibly more beginner friendly.

Update TESTS.md (dart test should also be a command people should know about)

---

CONTRIBUTING.md
docs/ABOUT.md
docs/INSTALLATION.md
docs/LEARNING.md
docs/RESOURCES.md
exercises/shared/.docs/help.md

changed urls from dartlang.org to dart.dev
fixes partially #364

changed a few urls

---

.github/workflows/links.yml
.github/workflows/test.yml

* Including --require-https flag as of version v1.1.1 will handle this

links.yml: Check links for https availability

---

bin/fetch-configlet
bin/fetch-configlet.ps1

The script has been tweaked to work better across all platforms.
Ref https://github.com/exercism/exercism/issues/6591

Update bin/fetch-configlet script

---

exercises/practice/acronym/.docs/instructions.md
exercises/practice/beer-song/.docs/instructions.md
exercises/practice/binary-search-tree/.docs/instructions.md
exercises/practice/bob/.docs/instructions.md
exercises/practice/darts/.docs/instructions.md
exercises/practice/diamond/.docs/instructions.md
exercises/practice/difference-of-squares/.docs/instructions.md
exercises/practice/hello-world/.docs/instructions.md
exercises/practice/leap/.docs/instructions.md
exercises/practice/minesweeper/.docs/instructions.md
exercises/practice/nth-prime/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/instructions.md
exercises/practice/raindrops/.docs/instructions.md
exercises/practice/resistor-color/.docs/instructions.md
exercises/practice/rna-transcription/.docs/instructions.md
exercises/practice/robot-simulator/.docs/instructions.md
exercises/practice/secret-handshake/.docs/instructions.md
exercises/practice/two-fer/.docs/instructions.md

This runs
bin/configlet sync --update --metadata --exercise SLUG
on any exercises that don't require any changes to their test suites in order to get up to date with the problem-specifications repository.
I generally prefer to update one exercise at a time, but reviewing gets quite tedious when there are lots of minor updates, so I went with a bulk update here.
A lot of the changes are formatting changes to adhere to the Exercism markdown specification, but there are also improvements to help clarify the instructions in exercises.

Sync docs for practice exercises

---

config.json
exercises/practice/pig-latin/.docs/hints.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.meta/config.json
exercises/practice/pig-latin/.meta/lib/example.dart
exercises/practice/pig-latin/.meta/tests.toml
exercises/practice/pig-latin/analysis_options.yaml
exercises/practice/pig-latin/lib/pig_latin.dart
exercises/practice/pig-latin/pubspec.yaml
exercises/practice/pig-latin/test/pig_latin_test.dart

Just thought I would try my hand at contributing a new Dart exercise - It's mainly adapted from the Java and C# tracks. I would appreciate any feedback, of course!

Add pig latin exercise

---

README.md

This adds a note about how to run the tests for a single exercise.

Tweak contribution documentation

---

exercises/practice/isbn-verifier/.docs/instructions.md
exercises/practice/isbn-verifier/.meta/config.json
exercises/practice/isbn-verifier/.meta/tests.toml
exercises/practice/isbn-verifier/test/isbn_verifier_test.dart

- Regenerate isbn-verifier
- Sync isbn-verifier with problem-specifications
This brings in updated instructions as well as a couple
of new tests.

Sync isbn-verifier with problem-specifications

---

exercises/practice/isogram/.docs/instructions.md
exercises/practice/isogram/.meta/config.json
exercises/practice/isogram/.meta/tests.toml
exercises/practice/isogram/test/isogram_test.dart

The first commit regenerates the test suite, which removes one level of nested grouping.
The second commit syncs with problem-specifications. Nothing exciting to see there!

Sync isogram with problem-specifications

---

exercises/practice/hamming/.docs/instructions.md
exercises/practice/hamming/.meta/config.json
exercises/practice/hamming/.meta/lib/example.dart
exercises/practice/hamming/.meta/tests.toml
exercises/practice/hamming/test/hamming_test.dart

This brings in updated instructions as well as a couple
of new tests and several reimplemented tests that changed
the expected error message.
Since the error messages don't really make a material difference
I didn't change the implementation to use the new messages.

Sync hamming with problem-specifications

---

exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/matching-brackets/.meta/config.json
exercises/practice/matching-brackets/.meta/tests.toml
exercises/practice/matching-brackets/test/matching_brackets_test.dart

This brings in improvements to the instructions as well
as some new tests.
The first commit regenerates the test suite in order to minimize the diff for the second commit, which does the actual sync.

Sync matching-brackets with problem specifications

---

exercises/practice/prime-factors/.docs/instructions.md
exercises/practice/prime-factors/.meta/config.json
exercises/practice/prime-factors/.meta/tests.toml
exercises/practice/prime-factors/test/prime_factors_test.dart

- Regenerate prime-factors to minimize diff when syncing
- Sync prime-factors with problem-specifications
This brings in improved instructions, ensures that the source url uses https
rather than http, and adds several new tests.

Sync prime-factors with problem-specifications

---

exercises/practice/triangle/.docs/instructions.md
exercises/practice/triangle/.meta/config.json
exercises/practice/triangle/.meta/tests.toml
exercises/practice/triangle/test/triangle_test.dart

The first commit regenerates the test suite to minimize changes when doing the sync.
The sync brings in improvements to the instructions, ensures that
the source url in the metadata is https rather than http, and
adds a couple of tests.

Sync triangle with problem-specifications

---

exercises/practice/leap/.meta/config.json
exercises/practice/leap/test/leap_test.dart

This allows types to be inferred in the
leap test suite.

Simplify assignments in leap

---

exercises/practice/pig-latin/.meta/config.json

This runs the `bin/configlet fmt --update` command to
reformat the exercise configs.

Reformat exercise config files

---

config.json
exercises/practice/high-scores/.docs/instructions.md
exercises/practice/high-scores/.meta/config.json
exercises/practice/high-scores/.meta/lib/example.dart
exercises/practice/high-scores/.meta/tests.toml
exercises/practice/high-scores/analysis_options.yaml
exercises/practice/high-scores/lib/high_scores.dart
exercises/practice/high-scores/pubspec.yaml
exercises/practice/high-scores/test/high_scores_test.dart

This is a proposal for a new exercise based on the canonical data in the problem-specifications repository.
I didn't make any design choices whatsoever—if you think a different API would be better suited to this exercise, please suggest some changes, and I will regenerate the test suite.
I put myself as contributor rather than author, since I don't intend to write the example solution.
As such, the authorship of this exercise is up for grabs to anyone who wants to spend a few minutes writing some code that will pass the tests.

Add stub for new exercise: high-scores

---

exercises/practice/gigasecond/lib/gigasecond.dart

Updated method name and position parameter for Gigasecond challenge for it to match the naming in tests.
https://github.com/exercism/dart/issues/475
https://github.com/exercism/dart/blob/1d3edb7afa27ca78725f30ee1015d727c3afdf05/exercises/practice/gigasecond/test/gigasecond_test.dart#L8

Update gigasecond.dart to match test naming

---

exercises/practice/all-your-base/.meta/config.json
exercises/practice/binary-search/.meta/config.json
exercises/practice/dnd-character/.meta/config.json
exercises/practice/matching-brackets/.docs/instructions.md
exercises/practice/matching-brackets/.docs/introduction.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/pig-latin/.docs/introduction.md
exercises/practice/roman-numerals/.meta/tests.toml
exercises/practice/roman-numerals/test/roman_numerals_test.dart
exercises/practice/space-age/.docs/instructions.md
exercises/practice/space-age/.docs/introduction.md
exercises/practice/yacht/.docs/instructions.md
exercises/practice/yacht/.docs/introduction.md
exercises/practice/yacht/.meta/config.json
exercises/practice/zebra-puzzle/.meta/config.json

Sync with recent probspec changes

---

exercises/practice/grade-school/test/grade_school_test.dart

This will not affect existing solutions, so add `[no important files changed]` to the merge comment.

grade-school: skip rest of tests

---

exercises/practice/grade-school/.meta/config.json
exercises/practice/hamming/.docs/instructions.md
exercises/practice/luhn/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/instructions.md
exercises/practice/pascals-triangle/.docs/introduction.md
exercises/practice/pig-latin/.docs/instructions.md
exercises/practice/protein-translation/.meta/tests.toml
exercises/practice/protein-translation/test/protein_translation_test.dart
exercises/practice/yacht/.meta/config.json
exercises/practice/zebra-puzzle/.docs/instructions.md
exercises/practice/zebra-puzzle/.docs/introduction.md

docs/filepaths/metadata/tests updates in separate commits.

Syncing recent problem spec changes

---

docs/LEARNING.md

This isn't a free resource, but all of Andrea's content is very high quality.
Having spent some time wading through extremely mediocre Dart and Flutter resources recently, it was a relief to find Andrea's stuff.
I'm not sure if Exercism is okay with linking to non-free resources, so I'll leave it up to the maintainer community to decide whether or not to bring this in.
Thanks, all! ❤️

Add a link to Andrea Bizzotto's Dart guide

---

docs/INSTALLATION.md

This also solves a link-checker problem.

Simplify the dart Installation page.

---

config.json
exercises/practice/bottle-song/.docs/instructions.md
exercises/practice/bottle-song/.meta/config.json
exercises/practice/bottle-song/.meta/lib/example.dart
exercises/practice/bottle-song/.meta/tests.toml
exercises/practice/bottle-song/analysis_options.yaml
exercises/practice/bottle-song/lib/bottle_song.dart
exercises/practice/bottle-song/pubspec.yaml
exercises/practice/bottle-song/test/bottle_song_test.dart

Add `bottle-song`
